name: Build Security Helpy

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build_macos_and_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos

      - name: Build iOS app (release)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/